
name: CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: ng build --prod
      
      - run: |
          git clone --depth 1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Maths-World-Web-Build.git /Maths-World-Web-Build
          cp -R dist/ /Maths-World-Web-Build/
          cd /Maths-World-Web-Build
          git add .
          git commit -m "chore: add new dist folder"
          git push
    
